Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2020-12, with the labels that each got.

#152 Use external VIP from the public network port
  modules/1_prepare/outputs.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  modules/5_install/versions.tf
  ocp.tf
  versions.tf
Labels: approved, backport, lgtm, size/M

#153 Use external VIP from the public network port
  modules/1_prepare/outputs.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  modules/5_install/versions.tf
  ocp.tf
  versions.tf
Labels: approved, backport, lgtm, size/M

#154 Documentation updates
  CONTRIBUTING.md
  LICENCE.txt
  README.md
Labels: approved, lgtm, size/S

#155 update helpernode commit
  variables.tf
Labels: approved, lgtm, size/XS

#158 update helpernode commit
  variables.tf
Labels: approved, backport, lgtm, size/XS

#157 update helpernode commit
  variables.tf
Labels: approved, backport, lgtm, size/XS

#133 validation and type check on variables #935
  modules/1_prepare/variables.tf
  variables.tf
Labels: approved, lgtm, size/L

#159 Increase the default memory for master nodes
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/XS

#163 IBM Cloud DirectLink support
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/powervs_config_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/M

#162 fix pull-secret path
  modules/5_install/install.tf
Labels: approved, lgtm, size/XS

#165 fix pull-secret path
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#167 minor fix for DL
  modules/5_install/install.tf
Labels: approved, lgtm, size/XS

#168 minor fix for DL
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#164 fix pull-secret path
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#169 minor fix for DL
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#161 Update python script link
  docs/ocp_prereqs_powervs.md
Labels: approved, do-not-merge/contains-merge-commits, ok-to-test, size/XS

#171 Bump up default min
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#160 Increase the default memory for master and bootstrap nodes
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S

#170 Misc doc fixes
  README.md
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/L

#173 Fix the install playbook failure due to default chrony config
  modules/5_install/templates/install_vars.yaml
Labels: approved, lgtm, size/XS

#174 workaround for RHEL 8.3 access bug
  modules/1_prepare/prepare.tf
Labels: approved, kind/bug, lgtm, size/S

#175 workaround for RHEL 8.3 access bug
  modules/1_prepare/prepare.tf
Labels: approved, backport, lgtm, size/S

#176 workaround for RHEL 8.3 access bug
  modules/1_prepare/prepare.tf
Labels: approved, backport, lgtm, size/S

#177 Use external VIP for bastion_ssh_command and add dns_entries output variable
  outputs.tf
Labels: approved, lgtm, size/S

#178 Use external VIP for bastion_ssh_command and add dns_entries output variable
  outputs.tf
Labels: approved, lgtm, size/S

#179 Use external VIP for bastion_ssh_command and add dns_entries output variable
  outputs.tf
Labels: approved, lgtm, size/S

#180 Update doc to use dns_entries output
  docs/quickstart.md
Labels: approved, lgtm, size/M

#181 Update doc to use dns_entries output
  docs/quickstart.md
Labels: approved, lgtm, size/M

#182 Update doc to use dns_entries output
  docs/quickstart.md
Labels: approved, lgtm, size/M

#186 Change Ansible installation to use yum
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#187 Change Ansible installation to use yum
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#188 Change Ansible installation to use yum
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#191 Cluster upgrade using stable versions
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#193 Cluster upgrade using stable versions
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S

#192 Cluster upgrade using stable versions
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S

#194 Update var.tfvars-doc.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/S

#195 trigger for upgrade resource
  modules/5_install/install.tf
Labels: approved, lgtm, size/XS

#197 trigger for upgrade resource
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#196 trigger for upgrade resource
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS
