Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2020-11, with the labels that each got.

#134 Use hostnames instead of IP in inventory
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
Labels: approved, backport, lgtm, size/S

#135 Update SSH keys path to use data directory
  variables.tf
Labels: approved, lgtm, size/XS

#136 Clarify usage of release-4.5 branch with OCP 4.5.x only
  README.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#137 Clarify usage of release-4.6 branch with OCP 4.6.x release
  README.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#132 doc firewall cfg
  docs/automation_host_prereqs.md
Labels: approved, backport, lgtm, size/XS

#138 Clarify use of master branch for latest OCP pre-release versions
  README.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#139 Doc changes
  docs/automation_host_prereqs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/M

#141 Minor changes to HA bastion description
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/XS

#140 Replace references to 4.5 with 4.6 and other minor doc updates
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/M

#144 IBM Cloud DirectLink support
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/powervs_config_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#145 Minor doc modifications
  README.md
Labels: approved, lgtm, size/XS

#146 IBM Cloud DirectLink support
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/powervs_config_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/M

#148 Fix DHCP configuration issue with network interface
  modules/5_install/install.tf
Labels: approved, lgtm, size/XS

#149 Use external VIP from the public network port
  modules/1_prepare/outputs.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  modules/5_install/versions.tf
  ocp.tf
  versions.tf
Labels: approved, lgtm, size/M

#150 Fix DHCP configuration issue with network interface
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#151 Fix DHCP configuration issue with network interface
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS
