Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2020-09, with the labels that each got.

#71 Improve Documentation
  README.md
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/M

#72 Add reference to IBM Cloud shell
  README.md
Labels: approved, lgtm, size/XS

#78 prevent bash expansion in password var
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#77 Add ignition fetch timeout
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/S

#81 Add ignition fetch timeout
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/S

#82 Misc Changes
  docs/quickstart.md
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#80 Support non-multipath SCSI disks for nfs volume
  modules/1_prepare/templates/create_disk_link.sh
Labels: approved, lgtm, size/S

#84 Support non-multipath SCSI disks for nfs volume
  modules/1_prepare/templates/create_disk_link.sh
Labels: approved, lgtm, size/S

#85 Move automation host setup to separate doc
  README.md
  docs/automation_host_prereqs.md
Labels: approved, lgtm, size/S

#87 Add TOC
  docs/automation_host_prereqs.md
  docs/var.tfvars-doc.md
Labels: approved, size/M

#88 Set DNS servers on public network
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
Labels: approved, lgtm, size/S

#90 Set DNS servers on public network
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
Labels: approved, lgtm, size/S

#89 Add TOC and README update
  README.md
  docs/automation_host_prereqs.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/M

#91 Set mtu on public network to 1450
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#92 Set mtu on public network to 1450
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#93 Add default route when network is already up
  modules/1_prepare/templates/fix_default_route.sh
Labels: approved, lgtm, size/M

#94 Add default route when network is already up
  modules/1_prepare/templates/fix_default_route.sh
Labels: approved, lgtm, size/M

#98 Change default config to suit CP4D
  var.tfvars
Labels: approved, lgtm, size/S

#96 Not wait for long to timeout during bastion destroy
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#97 Not wait for long to timeout during bastion destroy
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#86 moving secrets off var.tfvars file and to command line args
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#100 README warning about the README
  README.md
Labels: approved, lgtm, size/XS

#101 Doc fixes
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/M

#102 Set installer and client version in variables
  variables.tf
Labels: approved, lgtm, size/XS

#103 promoting error bullets to sections to HTML anchors work
  docs/known_issues.md
Labels: approved, backport, lgtm, size/L

#104 Update vars to use ocp 4.6 binary and image
  var.tfvars
Labels: approved, lgtm, size/XS
