Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2020-10, with the labels that each got.

#105 Remove section for ibmcloud plugin which is not needed
  docs/automation_host_prereqs.md
Labels: approved, lgtm, size/XS

#108 Update ocp4-playbook tag to include critical fixes
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/XS

#109 Add explicit links for terraform and IBM terraform provider plugin
  docs/automation_host_prereqs.md
Labels: approved, size/M

#110 Use the latest ibm provider plugin v1.13.0 and use the community ignition plugin v2.1
  docs/automation_host_prereqs.md
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/versions.tf
  versions.tf
Labels: approved, lgtm, size/M

#111 Misc doc changes
  docs/automation_host_prereqs.md
  docs/ocp_prereqs_powervs.md
Labels: approved, lgtm, size/S

#113 Fix interpolation-only warnings
  variables.tf
Labels: approved, lgtm, size/XS

#107 Upgrade to TF 0.13 and ibm plugin v1.13.0
  docs/automation_host_prereqs.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/versions.tf
  ocp.tf
  versions.tf
Labels: approved, lgtm, size/L

#115 Fix interpolation-only warnings
  variables.tf
Labels: approved, lgtm, size/XS

#114 Support bastion HA with external vip
  docs/var.tfvars-doc.md
  modules/1_prepare/outputs.tf
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/templates/helpernode_inventory
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
  modules/5_install/templates/install_vars.yaml
  modules/5_install/templates/keepalived_vrrp_instance.tpl
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#119 Fix the bastion count check
  variables.tf
Labels: approved, kind/bug, lgtm, size/XS

#120 Remove route fix script as route issue is fixed in latest plugin
  modules/1_prepare/prepare.tf
  modules/1_prepare/templates/fix_default_route.sh
Labels: approved, lgtm, size/M

#121 Remove dhcp hotfixes as not needed
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/M

#122 Allow multiple clusters (dhcpd) on same shared network
  modules/5_install/templates/install_vars.yaml
  variables.tf
Labels: approved, lgtm, size/XS

#117 Support bastion HA with external vip
  docs/var.tfvars-doc.md
  modules/1_prepare/outputs.tf
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/templates/helpernode_inventory
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
  modules/5_install/templates/install_vars.yaml
  modules/5_install/templates/keepalived_vrrp_instance.tpl
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#124 Changes from master related to routes and dhcp
  modules/1_prepare/prepare.tf
  modules/1_prepare/templates/fix_default_route.sh
  modules/4_nodes/nodes.tf
  modules/5_install/templates/install_vars.yaml
  variables.tf
Labels: approved, lgtm, size/M

#125 Add sydney region mapping
  docs/var.tfvars-doc.md
Labels: approved, lgtm, size/XS

#126 Support minimalistic 3-node OCP config
  docs/var.tfvars-doc.md
  modules/5_install/templates/helpernode_vars.yaml
  variables.tf
Labels: approved, lgtm, size/XS

#128 Correct the worker count check for helpernode
  modules/5_install/templates/helpernode_vars.yaml
Labels: approved, lgtm, size/XS

#127 Support minimalistic 3-node OCP config
  docs/var.tfvars-doc.md
  modules/5_install/templates/helpernode_vars.yaml
  variables.tf
Labels: approved, lgtm, size/XS

#130 Remove stale repo fix and improve subscription check
  modules/1_prepare/prepare.tf
Labels: approved, lgtm, size/XS

#129 Use hostnames instead of IP in inventory
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
Labels: approved, lgtm, size/S

#131 Remove stale repo fix and improve subscription check
  modules/1_prepare/prepare.tf
Labels: approved, backport, lgtm, size/XS
