Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-05, with the labels that each got.

#274 [release-4.6] Timeout added while removing worker node
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/XS

#273 [release-4.7] Timeout added while removing worker node
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/XS

#279 Move mtu settings to pre_install resource
  modules/5_install/install.tf
Labels: approved, lgtm, size/M

#276 Enable SNAT and disable Squid - default behavior
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#283 [release-4.6] Move mtu settings to pre_install resource
  modules/5_install/install.tf
Labels: approved, lgtm, size/M

#282 [release-4.7] Move mtu settings to pre_install resource
  modules/5_install/install.tf
Labels: approved, lgtm, size/M

#284 [release-4.7] Enable SNAT and disable Squid - default behavior
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#285 [release-4.6] Enable SNAT and disable Squid - default behavior
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#286 Fix Squid Proxy True PowerVS jobs are failing
  modules/5_install/install.tf
  modules/7_ibmcloud/dns.tf
Labels: approved, lgtm, size/XS

#287 [release-4.7] Fix Squid Proxy True PowerVS jobs are failing
  modules/5_install/install.tf
  modules/7_ibmcloud/dns.tf
Labels: approved, lgtm, size/XS

#271 Add zone info to instance name
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  modules/5_install/variables.tf
  modules/7_ibmcloud/dns.tf
  modules/7_ibmcloud/load_balancer.tf
  modules/7_ibmcloud/security_group.tf
  modules/7_ibmcloud/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#289 multipath fix for SAP netweaver image
  modules/1_prepare/templates/create_disk_link.sh
Labels: approved, lgtm, size/XS
