Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-01, with the labels that each got.

#202 Handle install after bootstrap is deleted
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
  variables.tf
Labels: approved, lgtm, size/S

#203 Handle install after bootstrap is deleted
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
  variables.tf
Labels: approved, backport, lgtm, size/S

#204 Handle install after bootstrap is deleted
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/install_inventory
  variables.tf
Labels: approved, backport, lgtm, size/S

#205 Allow adding and deleting worker nodes
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  ocp.tf
Labels: approved, enhancement, lgtm, size/M

#206 Allow adding and deleting worker nodes
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  ocp.tf
Labels: approved, lgtm, size/M

#207 Allow adding and deleting worker nodes
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  ocp.tf
Labels: approved, lgtm, size/M

#211 Update doc to be in sync with tfvars file
  docs/var.tfvars-doc.md
  var.tfvars
Labels: approved, lgtm, size/S

#210 Add actiovationkey support for RHEL subscription
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#214 update helpernode and install-playbook tags
  variables.tf
Labels: approved, backport, lgtm, size/XS

#213 update helpernode and install-playbook tags
  variables.tf
Labels: approved, backport, lgtm, size/XS

#212 update helpernode and install-playbook tags
  variables.tf
Labels: approved, lgtm, size/XS
