Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-04, with the labels that each got.

#255 Auto set volume type from the RHEL and RHCOS images
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#256 [release-4.7] Auto set volume type from the RHEL and RHCOS images
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#257 [release-4.6] Auto set volume type from the RHEL and RHCOS images
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  ocp.tf
  var.tfvars
Labels: approved, backport, lgtm, size/S

#247 Configure SNAT on bastion
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  variables.tf
Labels: approved, lgtm, size/M

#260 Backport PRs in release-4.7
  README.md
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#261 Backport PRs to release-4.6
  README.md
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#262 Add doc for SNAT and update offload settings to be used
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  var.tfvars
Labels: approved, lgtm, size/S

#263 Backport and align files in release-4.6 wrt master
  docs/automation_host_prereqs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#264 [release-4.7] Add doc for SNAT and update offload settings to be used
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  var.tfvars
Labels: approved, lgtm, size/S

#265 [release-4.6] Add doc for SNAT and update offload settings to be used
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  var.tfvars
Labels: approved, lgtm, size/S

#258 Format using terraform fmt
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  modules/1_prepare/outputs.tf
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/outputs.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
  versions.tf
Labels: approved, lgtm, size/XXL

#267 [release-4.7] Format using terraform fmt
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  modules/1_prepare/outputs.tf
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/outputs.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
  versions.tf
Labels: approved, backport, lgtm, size/XXL

#268 [release-4.6] Format using terraform fmt
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  modules/1_prepare/outputs.tf
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/1_prepare/versions.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/outputs.tf
  modules/4_nodes/versions.tf
  modules/5_install/install.tf
  modules/5_install/outputs.tf
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
  versions.tf
Labels: approved, backport, lgtm, size/XXL

#270 Timeout added while removing worker node
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/XS
