Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-07, with the labels that each got.

#312 Disable rx feature across reboots
  modules/5_install/install.tf
Labels: approved, lgtm, size/XS

#313 Update links to refer to OCP 4.8 version
  README.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#314 Minor changes to README
  README.md
Labels: approved, lgtm, size/S

#315 Update references to 4.8
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M
