Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-02, with the labels that each got.

#216 Create Terraform vars for test/dev cluster, CP4D, etc
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, ok-to-test, size/M

#218 Create Terraform vars for test/dev cluster, CP4D, etc for release branch 4.6
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#219 Create Terraform vars for test/dev cluster, CP4D, etc for release branch 4.5
  compute-vars/large.tfvars
  compute-vars/medium.tfvars
  compute-vars/small.tfvars
  docs/quickstart.md
  docs/var.tfvars-doc.md
Labels: approved, do-not-merge/contains-merge-commits, lgtm, ok-to-test, size/M

#220 Add variable to set default CNI network provider
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#221 Backport PRs to Release 4.6
  CONTRIBUTING.md
  LICENCE.txt
  README.md
  docs/automation_host_prereqs.md
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  modules/1_prepare/prepare.tf
  modules/1_prepare/variables.tf
  modules/5_install/templates/install_vars.yaml
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#222 Replace references to OCP 4.7
  README.md
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#224 Add variable to set default CNI network provider
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S
