Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2021-06, with the labels that each got.

#290 Improvements to load balacer topology
  modules/7_ibmcloud/dns.tf
  modules/7_ibmcloud/load_balancer.tf
  modules/7_ibmcloud/outputs.tf
Labels: approved, lgtm, size/L

#297 Update IBM Cloud services authentication
  docs/var.tfvars-doc.md
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#303 Update pre-req to include new steps for network connectivity
  docs/ocp_prereqs_powervs.md
Labels: approved, lgtm, size/M

#304 Add region info to cluster node's hostname
  modules/4_nodes/nodes.tf
  modules/5_install/install.tf
  modules/7_ibmcloud/dns.tf
Labels: approved, lgtm, size/S
