Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2022-06, with the labels that each got.

#412 Imports image from object store to PVS
  docs/var.tfvars-doc.md
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: lgtm, size/L, approved

#419 Add upgrade_image option
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: lgtm, size/S, ok-to-test, approved

#414 Turn off rx for all interfaces to improve performance
  modules/1_prepare/prepare.tf
  modules/5_install/install.tf
Labels: lgtm, size/M, approved

#423 csi driver installation minor fix
  modules/5_install/install.tf
Labels: kind/bug, size/XS, lgtm, approved

#422 To Automate Node Labels
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: lgtm, size/M, approved

#427 Install latest ansible with required modules.
  modules/1_prepare/prepare.tf
Labels: size/XS, lgtm, approved

#432 Add rpsene and aishwaryabk as reviewer, remove bpradipt as approver
  OWNERS
Labels: size/XS, lgtm, approved
