Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2023-02, with the labels that each got.

#463 Include ppc64le hash
  .terraform.lock.hcl
Labels: size/XS, lgtm, approved

#462 Update defaults and docs to latest stable OCP version
  CONTRIBUTING.md
  README.md
  docs/ocp_prereqs_powervs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: lgtm, size/L, approved

#461 fix: compact cluster provisions
  modules/5_install/install.tf
Labels: size/XS, lgtm, ok-to-test, approved

#466 Minor doc update for getting list of system types
  docs/var.tfvars-doc.md
Labels: size/XS, lgtm, approved

#467 Adding minor change related to doc file
  docs/var.tfvars-doc.md
Labels: size/XS, lgtm, ok-to-test, approved

#468 Update ppc64le hash for v0.15 set of archive
  .terraform.lock.hcl
Labels: size/XS, lgtm, approved
