Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2023-11, with the labels that each got.

#497 Replace Classic DNS with CIS
  docs/quickstart.md
  docs/var.tfvars-doc.md
  modules/7_ibmcloud/dns.tf
  modules/7_ibmcloud/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: lgtm, size/L, approved

#498 Support adding DNS entries for CIS service based cluster domain
  docs/quickstart.md
  modules/8_custom/cis.tf
  modules/8_custom/variables.tf
  modules/8_custom/versions.tf
  ocp.tf
Labels: lgtm, size/L, approved

#500 enforce resource_group constraints on VPC resources #499
  modules/7_ibmcloud/load_balancer.tf
  modules/7_ibmcloud/security_group.tf
Labels: size/XS, lgtm, approved

#501 Correct resource dependencies in case of subsequent runs
  modules/5_install/install.tf
Labels: lgtm, size/S, approved

#504 Remove xip.io as wildcard DNS
  docs/quickstart.md
  docs/var.tfvars-doc.md
  modules/4_nodes/nodes.tf
  modules/5_install/install.tf
  outputs.tf
  var.tfvars
Labels: lgtm, size/S, approved
