Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2023-06, with the labels that each got.

#475 fix: default region for cos to au-syd
  ocp.tf
Labels: size/XS, lgtm, approved

#473 Add automated rhcos image file name markdown generator
  .github/workflows/rhcos_generate.yml
Labels: size/M, approved

#477 update the footer message
  .github/workflows/rhcos_generate.yml
Labels: size/XS, lgtm, approved

#479 Improve handling of shutdown and startup actions
  modules/4_nodes/nodes.tf
  ocp.tf
Labels: size/XS, lgtm, ok-to-test, approved

#482 Upgrade IBM-Cloud provider version
  modules/1_prepare/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/versions.tf
  modules/7_ibmcloud/versions.tf
  versions.tf
Labels: size/S, approved, do-not-merge/non-mergeable
