Repository ocp-power-automation/ocp4-upi-powervs, pull requests merged in 2024-02, with the labels that each got.

#514 Freeze time provider version
  modules/1_prepare/versions.tf
Labels: size/XS, approved, do-not-merge/non-mergeable

#515 Add support for additional PER data centers
  ocp.tf
Labels: size/XS, lgtm, approved

#516 Added wdc to use us-east vpc region for image import
  ocp.tf
Labels: lgtm, size/S, approved

#518 Replace the local registry image with the official multi-arch registry image
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: size/XS, lgtm, approved
